### ISSUE TITLE
Install Image Mirror Digest when working with Konflux

### ISSUE THREAD

**Issue by sarroutbi** [RedHat-SP-Security/tang-operator-tests#128]
When working with Konflux, references to containers are of the type: `registry.redhat.io/...`

However, this kind of images are not accessible (yet) until release is performed.

To work with them, an Image Mirror Digest can be set. In this case, it should be something similar like:

```yaml
---
kind: ImageDigestMirrorSet
apiVersion: config.openshift.io/v1
metadata:
  name: nbde-tang-server-fbc-staging-index
  namespace: openshift-marketplace
spec:
  imageDigestMirrors:
    - source: registry.redhat.io/nbde-tang-server/nbde-tang-server-operator-bundle
      mirrors:
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-bundle-1-1
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-bundle
    - source: registry.redhat.io/nbde-tang-server/nbde-tang-server-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-1-1
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch
    - source: registry.stage.redhat.io/nbde-tang-server/nbde-tang-server-operator-bundle
      mirrors:
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-bundle-1-1
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-bundle
    - source: registry.stage.redhat.io/nbde-tang-server/nbde-tang-server-rhel9-operator
      mirrors:
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch-1-1
        - quay.io/redhat-user-workloads/konflux-sec-eng-spec-tenant/nbde-tang-server-multiarch
```

So, when working with Konflux, this configuration must be applied
